### ISSUE TITLE
Sophos XG and HTTPS external url lists

### ISSUE THREAD

**Issue by d0csys** [austinheap/sophos-xg-block-lists#3]
First, and foremost thank you for your efforts on this project @austinheap !

I am having some issues importing these lists into the Sophos XG, mainly because the XG only takes lists which are HTTP, and not HTTPS.  

The links labeled HTTP appear to be unreachable (404), and i see the host redirecting to the HTTPS equivalent, an example being:
https://sophos-xg-block-lists.austinheap.com/easyprivacy.txt

The HTTPS links work, as they're hosted by Github.
example: https://raw.githubusercontent.com/austinheap/sophos-xg-block-lists/master/adguard.txt

I have tried entering the Github URL as HTTP, since it will redirect to HTTPS anyways, and i figured it would "trick" the sophos UTM to pull the list anyhow, but it has not worked.  Silly they only allow HTTP based lists.

Thank you,
Rick

**Comment by austinheap** [comment]
@d0csys Glad it's helpful! Give it another shot, should be fixed now.

**Comment by d0csys** [comment]
Unfortunately, the links are still broken on my end, indicating a 404 error. I spot checked a few other HTTP links, and had the same issue.

404 Not Found
nginx

**Comment by austinheap** [comment]
Weird... I've tested from multiple locations successfully. Can you share the output from `curl -s http://sophos-xg-block-lists.austinheap.com/easyprivacy.txt`? Please note HTTPS/SSL will _never_ be available on the domain `sophos-xg-block-lists.austinheap.com`.

**Comment by austinheap** [comment]
Closing for now. Feel free to re-open if the issue persists.

**Comment by nagug** [comment]
Looks like this is open. I also have the same issue of unable to load due to 404 on http
